### ISSUE TITLE
Implement new design tokens to the chip component

### ISSUE THREAD

**Issue by vicenteopaso** [peterbb148/malty#7]
Implement New Design Tokens for the malty/atoms/Chip component, following implementation of malty/theme/NewMaltyThemeProvider/NewMaltyThemeProvider.tsx, to be imported from '@carlsberg/malty.theme.new-malty-theme-provider'

Make sure to look at new types structure, and use the exported objects to replace existing implementation of current MaltyThemeProvider. Make sure values are accessed directly, and not with the existing '.value' structure. In other words '2xs' is accessed directly, and not as ['2xs'].value
This is true for all tokens, not only sizes, but colors, etc.

Ensure to completely remove existing theme from component implementation.

Ensure helpers in the NewMaltyThemeProvider are used where necessary.

Make sure the Storybook stories are updated, as well as visual regression tests, where necessary. Do not import the new theme provider in the story, follow existing implementation.

**Comment by acpcor** [comment]
Regarding the color tokens: 

- theme.colors.colours.support[20].value should be replaced by theme.colorsV2.default.neutral[50]
- theme.colors.colours.support[80].value should be replaced by theme.colorsV2.default.neutral[600]
- theme.colors.colours.support[100].value should be replaced by theme.colorsV2.default.neutral[900]
- theme.colors.colours.system['disable-light-theme'].value should be replaced by theme.colorsV2.default.neutral[200]
